2025-08-17 22:12:30,509 [INFO] Step-1: Folder created: uploads/0a547404-8c44-4236-8fa6-cb13fbb5023a
2025-08-17 22:12:30,512 [INFO] Using Python executable: venv/bin/python3
2025-08-17 22:12:30,512 [INFO] Step-2: File sent {'question.txt': 'uploads/0a547404-8c44-4236-8fa6-cb13fbb5023a/question.txt'}
2025-08-17 22:12:30,512 [INFO] 🤖 Step-1: Getting scrap code and metadata from llm. Tries count = 0
2025-08-17 22:12:38,843 [INFO] 🤖 Step-1: Successfully parsed response from LLM.
2025-08-17 22:12:38,843 [INFO] 💻 Step-3: Entering loop
2025-08-17 22:12:38,843 [INFO] 💻 Loop-1: Running LLM code.
2025-08-17 22:12:41,419 [INFO] ✅💻 Loop-1: Code executed successfully.
2025-08-17 22:12:41,419 [INFO] 🤖 Loop-1: Inside Loop LLM call.
2025-08-17 22:13:22,723 [INFO] 💻 Loop-2: Running LLM code.
2025-08-17 22:13:27,582 [ERROR] ❌💻 Loop-2: Code execution failed: ❌ Execution error: Traceback (most recent call last): File "/home/sabya/TDS_project2/uploads/0a547404-8c44-4236-8fa6-cb13fbb5023a/job_/script.py", line 37, in <module> df['Worldwide gross'] = df['Worldwide gross'].apply(clean_gross) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/sabya/TDS_project2/venv/lib/python3.12/site-packages/pandas/core/series.py", line 4935, in apply ).apply() ^^^^^^^ File "/home/sabya/TDS_project2/venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1422, in apply return self.apply_standard() ^^^^^^^^^^^^^^^^^^^^^ File "/home/sabya/TDS_project2/venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1502, in apply_standard mapped = obj._map_values( ^^^^^^^^^^^^^^^^ File "/home/sabya/TDS_project2/venv/lib/python3.12/site-packages/pandas/core/base.py", line 925, in _map_values return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/sabya/TDS_project2/venv/lib/python3.12/site-packages/pandas/core/algorithms.py", line 1743, in map_array return lib.map_infer(values, mapper, convert=convert) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "pandas/_libs/lib.pyx", line 2999, in pandas._libs.lib.map_infer File "/home/sabya/TDS_project2/uploads/0a547404-8c44-4236-8fa6-cb13fbb5023a/job_/script.py", line 35, in clean_gross return int(gross_str.replace('$', '').replace(',', '')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: invalid literal for int() with base 10: 'T2257844554'
2025-08-17 22:13:27,583 [INFO] 🤖 Loop-2: Inside Loop LLM call.
2025-08-17 22:14:38,232 [INFO] 💻 Loop-3: Running LLM code.
2025-08-17 22:14:42,766 [INFO] ✅💻 Loop-3: Code executed successfully.
2025-08-17 22:14:42,766 [INFO] ✅📁 Loop-3: Found result files.
2025-08-17 22:14:42,766 [INFO] 🤖 Loop-3: Checking result validity.
2025-08-17 22:14:53,713 [INFO] ✅ Loop-3: Validation successful, no re-run needed.
2025-08-17 22:14:53,713 [INFO] 💻 Step-6: Running final code.
2025-08-17 22:14:53,731 [INFO] 📁 Step-7: Reading result.json
2025-08-17 22:14:53,731 [INFO] ✅📁 Step-7: send result back
